### PR TITLE
Completed Climb subsystem logic

### LINKED ISSUE #38: CLean up Java warnings about non-ASCII characters
/__w/2026_Rebuilt/2026_Rebuilt/CompBot/src/main/java/frc/robot/generated/TestBotTunerConstants.java:265: error: unmappable character (0xE1) for encoding US-ASCII
         *                                  in the form [x, y, theta]???, with units in meters
 
All of the theta]??? comments could be converted to something ASCII and these build warnings will go away.

### PR DESCRIPTION
**Pull request by Foon974**
We have updated the logic to reflect the level 0 and level 1 climb instead of having those levels with levels 2 and 3 as well.
Closes #38 
(issue 38 is closed because we added the ASCII fixes here)

### CODE REVIEW

File: CompBot/src/main/java/frc/robot/subsystems/climber/Climber.java [hunk 1]
```diff
@@ -9,11 +15,47 @@ public class Climber extends SubsystemBase {
 
   public Climber(ClimberIO io) {
     this.io = io;
+    SmartDashboard.putData("Climber/ClimbTo0", climb(CLIMBERPOSITIONS_ENUM.LEVEL0));
```
Comment (therekrab) [inline CompBot/src/main/java/frc/robot/subsystems/climber/Climber.java]: 1. You don't need to name your enum `_ENUM`
2. Although snake case is common in several other projects, you should probably just use `PascalCase` here, just to match with our conventions.
3. Maybe rename level 0 to `NotClimbed`. There's no reason to assosciate climb positions with integers.

File: CompBot/src/main/java/frc/robot/subsystems/climber/ClimberIOSim.java [hunk 2]
```diff
@@ -8,9 +8,11 @@
 import edu.wpi.first.units.measure.Voltage;
 import edu.wpi.first.wpilibj.simulation.DCMotorSim;
 import frc.robot.Robot;
+import frc.robot.subsystems.climber.ClimberConstants.CLIMBERPOSITIONS_ENUM;
 
 public class ClimberIOSim implements ClimberIO {
   private final DCMotorSim motor;
+  private double position = 0;
```
Comment (therekrab) [inline CompBot/src/main/java/frc/robot/subsystems/climber/ClimberIOSim.java]: Use units, not doubles. WPILib has `Angle` for motor positions.

File: CompBot/src/main/java/frc/robot/subsystems/climber/ClimberIOSim.java [hunk 3]
```diff
@@ -30,4 +33,14 @@ public void updateInputs(ClimberIOInputs inputs) {
...
+
+  public void climb(CLIMBERPOSITIONS_ENUM climbLevel) {
+    switch(climbLevel) {
+      case LEVEL0:
+      position = ClimberConstants.kLevelZeroPosition;
+        break;
+      default:
+      position = ClimberConstants.kLevelOnePosition;
+    }
+  }
```
Comment (therekrab) [inline CompBot/src/main/java/frc/robot/subsystems/climber/ClimberIOSim.java]: This is why the position selection logic should be moved into `Climber itself`; your logic to switch the position doesn't have any business being repeated twice in both IO implementations. I'd rather implement it once in the `Climber` class. Plus, it's too high-level for this class.

File: CompBot/src/main/java/frc/robot/subsystems/drivetrain/Drivetrain.java [hunk 4]
```diff
@@ -259,7 +259,7 @@ public void addVisionMeasurement(Pose2d visionRobotPoseMeters, double timestampS
    * @param visionRobotPoseMeters The pose of the robot as measured by the vision camera.
    * @param timestampSeconds The timestamp of the vision measurement in seconds.
    * @param visionMeasurementStdDevs Standard deviations of the vision pose measurement in the form
-   *        [x, y, theta]ᵀ, with units in meters and radians.
+   *        [x, y, theta]^T, with units in meters and radians.
```
Comment (therekrab) [inline CompBot/src/main/java/frc/robot/subsystems/drivetrain/Drivetrain.java]: THANK YOU

File: CompBot/src/main/java/frc/robot/subsystems/climber/ClimberIO.java [hunk 5]
```diff
@@ -19,6 +22,7 @@ class ClimberIOInputs {
     public Current statorCurrent = Amps.zero();
     public Voltage voltage = Volts.zero();
     public Temperature temperature = Celsius.zero();
+    public double position = 0;
```
Comment (therekrab) [inline CompBot/src/main/java/frc/robot/subsystems/climber/ClimberIO.java]: Use units here, too.

File: CompBot/src/main/java/frc/robot/subsystems/climber/ClimberConstants.java [hunk 6]
```diff
@@ -13,6 +13,20 @@ public final class ClimberConstants {
   protected static final double kSupplyCurrentLimit = 40.0;
   protected static final double kStatorCurrentLimit = 125.0;
 
+  protected static enum CLIMBERPOSITIONS_ENUM {
```
Comment (therekrab) [inline CompBot/src/main/java/frc/robot/subsystems/climber/ClimberConstants.java]: Take a look at [this](https://therekrab.github.io/frc-programming-reference/advanced/structure/3_1_1_subsystems.html#use-enums-extensively) page in the reference doc to see how to associate positions with their enum variants, so you don't need such strangely coupled constants. HOWEVAA, don't use `double` objects like the docs say (I gotta fix that), instead use `Angle`.

File: CompBot/src/main/java/frc/robot/subsystems/climber/ClimberIOHardware.java [hunk 7]
```diff
@@ -3,20 +3,24 @@
...
 public class ClimberIOHardware implements ClimberIO {
   private final TalonFX motor;
 
+  private final DynamicMotionMagicVoltage control;
   private Voltage lastVoltage = Volts.zero();
 
   public ClimberIOHardware() {
     motor = new TalonFX(ClimberConstants.kMotorID);
     motor.getConfigurator().apply(ClimberConstants.kMotorConfig);
+    control = new DynamicMotionMagicVoltage(ClimberConstants.kMaxSpeed, ClimberConstants.kMaxVelocity, ClimberConstants.kMaxAcceleration);
```
Comment (therekrab) [inline CompBot/src/main/java/frc/robot/subsystems/climber/ClimberIOHardware.java]: You can move the definition up a little bit to L17 so it doesn't clutter the constructor.

File: CompBot/src/main/java/frc/robot/subsystems/climber/Climber.java [hunk 8]
```diff
@@ -9,11 +15,47 @@ public class Climber extends SubsystemBase {
...
+              Commands.waitUntil(ready(climbLevel)));
+        }
+    }
 
+    // If not in the right place to climb, do nothing
+    return Commands.none();
+
+  }
+
+  private Trigger ready(CLIMBERPOSITIONS_ENUM climbLevel) {
```
Comment (therekrab) [inline CompBot/src/main/java/frc/robot/subsystems/climber/Climber.java]: You can make this public

File: CompBot/src/main/java/frc/robot/subsystems/climber/ClimberIOHardware.java [hunk 9]
```diff
@@ -3,15 +3,19 @@
...
 import com.ctre.phoenix6.hardware.TalonFX;
 
+import edu.wpi.first.units.measure.Angle;
 import edu.wpi.first.units.measure.Voltage;
 import frc.robot.util.StatusSignalUtil;
 
 public class ClimberIOHardware implements ClimberIO {
   private final TalonFX motor;
 
+  private final DynamicMotionMagicVoltage control = new DynamicMotionMagicVoltage(ClimberConstants.kCruiseVelocity, ClimberConstants.kJerk, ClimberConstants.kAcceleration);
```
Comment (therekrab) [inline CompBot/src/main/java/frc/robot/subsystems/climber/ClimberIOHardware.java]: 1. We're trying this season to use the [`DynamicMotionMagicTorqueCurrentFOC`](https://api.ctr-electronics.com/phoenix6/stable/java/com/ctre/phoenix6/controls/DynamicMotionMagicTorqueCurrentFOC.html) control request because technically field-oriented control is more performant.
2. Make sure that that the arguments you pass are correct; it doesn't seem that way. This definitely needs to change before we merge this.

File: CompBot/src/main/java/frc/robot/subsystems/climber/ClimberIOHardware.java [hunk 10]
```diff
@@ -48,5 +54,14 @@ public void setVoltage(Voltage voltage) {
       lastVoltage = voltage;
     }
   }
+
+  public void setPosition(Angle position) {
+    if (position == ClimberConstants.kUnclimbedPosition) {
```
Comment (therekrab) [inline CompBot/src/main/java/frc/robot/subsystems/climber/ClimberIOHardware.java]: 1. for future reference the `==` operator doesn't work on non-primative types; it compares the memory addresses, not the values. Use `.equals()` instead.

2. I don't understand this logic at all; is this `if` statement necessary?
